# Generated by Django 3.1.7 on 2021-03-14 16:39

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('cover', models.FileField(upload_to='cover_product')),
                ('discripton', ckeditor.fields.RichTextField()),
                ('create_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
